[build]
  command = "echo 'No build step needed'"
  publish = "."

[functions]
  included_files = ["netlify/functions/**/*.js"]

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "netlify dev"
  targetPort = 8888
  envFile = ".env"

[[plugins]]
  package = "@netlify/plugin-nextjs" 