[build]
  command = "echo 'No build step needed'"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/**/*.js"]

[dev]
  command = "netlify dev"
  targetPort = 8888
  envFile = ".env"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# By defining an empty plugins array, we prevent Netlify's build system
# from automatically detecting and applying the Next.js plugin. 