[build]
  command = "mkdir -p dist && cp index.html dist/ && cp -r images dist/ && cp -r fonts dist/"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_ESBUILD = "true"

[dev]
  command = "netlify dev"
  targetPort = 8888
  envFile = ".env"

[[plugins]]
  package = "@netlify/plugin-functions-core" 